name: Test and Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'

jobs:
  # ============================================================================
  # JOB 1: RUN UNIT TESTS
  # This job runs first. It installs Python and the test dependencies,
  # then executes the unit tests for our Lambda functions.
  # ============================================================================
  test:
    name: 'Run Lambda Unit Tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 moto

      - name: Run unit tests
        # This command discovers and runs all tests inside the specified directory.
        run: python -m unittest discover infrastructure/lambda/tests

  # ============================================================================
  # JOB 2: DEPLOY INFRASTRUCTURE
  # This job will only start if the 'test' job completes successfully.
  # ============================================================================
  deploy:
    name: 'Deploy to AWS'
    runs-on: ubuntu-latest
    needs: test # This line is crucial - it links the jobs.

    permissions:
      contents: read

    defaults:
      run:
        working-directory: ./infrastructure

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve

  

        