name: Test and Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'

jobs:
  # ============================================================================
  # JOB 1: RUN UNIT TESTS
  # ============================================================================
  test:
    name: 'Run Lambda Unit Tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 moto pytest

      - name: Run unit tests
        env:
          AWS_DEFAULT_REGION: us-east-2
          PROCESSED_TABLE_NAME: dummy-table
          QUARANTINE_BUCKET_NAME: dummy-bucket
        run: pytest -v infrastructure/lambda/tests

  # ============================================================================
  # JOB 2: DEPLOY INFRASTRUCTURE
  # ============================================================================
  deploy:
    name: 'Deploy to AWS'
    runs-on: ubuntu-latest
    needs: test # Only runs if 'test' succeeds.

    permissions:
      contents: read

    defaults:
      run:
        working-directory: ./infrastructure

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # Must match provider config

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve




  

        